apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  type: NodePort
  selector:
    app: service-b
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v12
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 1
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: service-b
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80