apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: service-a
build:
  artifacts:
    - image: service-a
deploy:
  kubectl:
    manifests:
      - multi-env-config/svc-config/dev/servic-a/dev-deployment.yaml
      - multi-env-config/svc-config/prod/servic-a/prod-deployment.yaml