apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v12
kind: Deployment
metadata:
  name: service-a-deployment
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: service-a
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80