apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: service-b
build:
  artifacts:
    - image: service-b
deploy:
  kubectl:
    manifests:
      - multi-env-config/svc-config/dev/servic-b/dev-deployment.yaml
      - multi-env-config/svc-config/prod/servic-b/prod-deployment.yaml