apiVersion: v1
kind: Service
metadata:
  name: multi-env-config-service
  labels:
    app: multi-env-config
spec:
  type: NodePort
  selector:
    app: multi-env-config
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-env-config-deployment
  labels:
    app: multi-env-config
spec:
  selector:
    matchLabels:
      app: multi-env-config
  replicas: 1
  template:
    metadata:
      labels:
        app: multi-env-config
    spec:
      containers:
        - name: multi-env-config
          image: multi-env-config
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80