apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: multi-env-config
build:
  artifacts:
    - image: multi-env-config
deploy:
  kubectl:
    manifests:
      - dev-deployment.yaml
      - prod-deployment.yaml
portForward:
- resourceType: deployment
  resourceName: multi-env-config-deployment
  port: 80
  localPort: 80