apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: multi-env-config
build:
  artifacts:
    - image: multi-env-config
deploy:
  kubectl:
    manifests:
      - ../multi-env-config/svc-config/dev/multi-env-config/deployment.yaml